---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  # yamllint disable
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   Off

    @INCLUDE input.conf
    @INCLUDE filters.conf
    @INCLUDE output-stdout.conf
    @INCLUDE output-nats.conf

  input.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filters.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Keep_Log            Off

    [FILTER]
        Name grep
        Match *
        Regex $kubernetes['namespace_name'] pl$
    
    [FILTER]
        Name grep
        Match *
        Exclude $kubernetes['container_name'] fluent-bit

    [FILTER]
        Name grep
        Match *
        Exclude $kubernetes['container_name'] nats-watcher

    # NOTE(james): these two filters are necessary because query-broker uses both glog and logfmt formats
    # so we have to explicitly try to parse the lines that aren't logfmt in that case.
    [FILTER]
        Name parser
        Match *
        Parser glog_prefixed
        Key_Name log
        Reserve_Data On

    [FILTER]
        Name nest
        Match *
        Operation nest
        Wildcard glog_*
        Nest_under log_processed
        Remove_prefix glog_

    [FILTER]
        Name grep
        Match *
        Exclude $log_processed['req_path'] /healthz

  output-stdout.conf: |
    [OUTPUT]
        Name            stdout
        Match           *
        Format          json

  output-nats.conf: |
    [OUTPUT]
        Name            natstls
        Match           *
        nats_host       pl-nats
        nats_port       4222
        tls_client_cert_file /certs/client.crt
        tls_client_key_file  /certs/client.key
        tls_ca_cert_file     /certs/ca.crt

  parsers.conf: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep On
        Decode_Field_As escaped_utf8 log
    [PARSER]
        Name   logfmt
        Format logfmt
    [PARSER]
        Name   glog
        Format regex
        Regex   ^(?<level>[IWEF])(?<time>[0-9]+ [0-9.:]+)\s+(?<thread_id>[0-9]+)\s+(?<file>[\w.]+):(?<line>[0-9]+)](?<msg> .*$)
        Time_Key time
        Time_Format %m%d %H:%M:%S.%L
    [PARSER]
        Name   glog_prefixed
        Format regex
        Regex   ^(?<glog_level>[IWEF])(?<glog_time>[0-9]+ [0-9.:]+)\s+(?<glog_thread_id>[0-9]+)\s+(?<glog_file>[\w.]+):(?<glog_line>[0-9]+)](?<glog_msg> .*$)
        Time_Key time
        Time_Format %m%d %H:%M:%S.%L
    [PARSER]
        # https://rubular.com/r/3fVxCrE5iFiZim
        Name    envoy
        Format  regex
        Regex ^\[(?<start_time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)? (?<protocol>\S+)" (?<code>[^ ]*) (?<response_flags>[^ ]*) (?<bytes_received>[^ ]*) (?<bytes_sent>[^ ]*) (?<duration>[^ ]*) (?<x_envoy_upstream_service_time>[^ ]*) "(?<x_forwarded_for>[^ ]*)" "(?<user_agent>[^\"]*)" "(?<request_id>[^\"]*)" "(?<authority>[^ ]*)" "(?<upstream_host>[^ ]*)"
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
        Time_Key start_time
