apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sharelatex
  name: sharelatex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sharelatex
    spec:
      containers:
      - env:
        - name: SHARELATEX_APP_NAME
          value: Our ShareLaTeX
        - name: SHARELATEX_MONGO_URL
          value: mongodb://mongo/sharelatex
        - name: SHARELATEX_REDIS_HOST
          value: redis
        image: rigon/sharelatex-full:latest
        name: sharelatex
        ports:
        - containerPort: 80
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/sharelatex
          name: sharelatex-claim0
      restartPolicy: Always
      volumes:
      - name: sharelatex-claim0
        persistentVolumeClaim:
          claimName: sharelatex-claim0
status: {}
