---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pl
resources:
- ../base
- ../pem
patches:
# yamllint disable rule:indentation
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: PL_PROFILER_JAVA_SYMBOLS
        value: "0"
# yamllint enable rule:indentation
  target:
    kind: DaemonSet
    namespace: pl
    name: vizier-pem
