---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: pl-monitoring
  component: vizier
kind: Kustomization
namespace: pl
patches:
- path: patch_sentry.yaml
  target:
    kind: Deployment
    labelSelector: vizier-bootstrap!=true
resources:
- ../bootstrap
- proxy_envoy.yaml
- certmgr_role.yaml
- certmgr_deployment.yaml
- certmgr_service.yaml
- kelvin_deployment.yaml
- kelvin_service.yaml
- metadata_role.yaml
- metadata_service.yaml
- node_view_cluster_role.yaml
- pem_daemonset.yaml
- proxy_deployment.yaml
- proxy_service.yaml
- query_broker_deployment.yaml
- query_broker_service.yaml
- tls_config.yaml
