---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metadata-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pl-vizier-metadata
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pl-vizier-metadata-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pl-vizier-metadata
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: pl
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pl-vizier-crd-metadata-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pl-vizier-crd-role
subjects:
- kind: ServiceAccount
  name: metadata-service-account
  namespace: pl
