---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plc
commonLabels:
  app: pl-cloud
resources:
- elastic
- kibana
- nats
- stan
patches:
- path: node_selector_patch.yaml
  target:
    kind: StatefulSet
