---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-watcher
  template:
    metadata:
      name: nats-watcher
      labels:
        app: nats-watcher
        name: nats-watcher
    spec:
      containers:
      - image: gcr.io/pixie-oss/pixie-dev-public/vizier/nats_watcher_image:latest
        name: nats-watcher
        env:
        - name: PL_SERVER_TLS_CERT
          value: /certs/server.crt
        - name: PL_SERVER_TLS_KEY
          value: /certs/server.key
        - name: PL_CLIENT_TLS_CERT
          value: /certs/client.crt
        - name: PL_CLIENT_TLS_KEY
          value: /certs/client.key
        - name: PL_TLS_CA_CERT
          value: /certs/ca.crt
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
