---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plugin-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: plugin-server
  template:
    metadata:
      labels:
        name: plugin-server
    spec:
      containers:
      - name: plugin-server
        image: gcr.io/pixie-oss/pixie-dev/cloud/plugin_server_image
        ports:
        - containerPort: 50600
          name: http2
        - containerPort: 50601
          name: metrics-http
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50600
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 50600
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_USERNAME
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_PASSWORD
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
