---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scriptmgr-server
spec:
  selector:
    matchLabels:
      name: scriptmgr-server
  template:
    metadata:
      labels:
        name: scriptmgr-server
    spec:
      containers:
      - name: scriptmgr-server
        image: gcr.io/pixie-oss/pixie-dev/cloud/scriptmgr_server_image
        ports:
        - containerPort: 52000
          name: http2
        - containerPort: 52001
          name: metrics-http
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 52000
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 52000
        envFrom:
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-scriptmgr-config
        - configMapRef:
            name: pl-domain-config
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
