---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vzmgr-server
  labels:
    db: pgsql
spec:
  selector:
    matchLabels:
      name: vzmgr-server
  template:
    metadata:
      labels:
        name: vzmgr-server
    spec:
      containers:
      - name: vzmgr-server
        image: gcr.io/pl-dev-infra/cloud/vzmgr_server_image
        ports:
        - containerPort: 51800
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51800
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 51800
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-tls-config
        - configMapRef:
            name: pl-domain-config
        env:
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        - name: PL_DATABASE_KEY
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: database-key
        - name: PL_DNSMGR_SERVICE
          valueFrom:
            configMapKeyRef:
              name: pl-service-config
              key: PL_DNSMGR_SERVICE
        - name: PL_ARTIFACT_TRACKER_SERVICE
          valueFrom:
            configMapKeyRef:
              name: pl-service-config
              key: PL_ARTIFACT_TRACKER_SERVICE
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_USERNAME
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_PASSWORD
        - name: PL_SEGMENT_WRITE_KEY
          valueFrom:
            secretKeyRef:
              name: segment-secrets
              key: write-key
        volumeMounts:
        - name: certs
          mountPath: /certs
      volumes:
      - name: certs
        secret:
          secretName: service-tls-certs
