---
apiVersion: batch/v1
kind: Job
metadata:
  name: plugin-db-updater-job
  labels:
    jobgroup: plugin-db-updater
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      name: plugin-db-updater-job
      labels:
        jobgroup: plugin-db-updater
    spec:
      initContainers:
      - name: postgres-wait
        # TODO(ddelnano): This image was rebuilt from https://github.com/docker-library/postgres 14-alpine
        # to remediate a critical vulnerability. Switch back to upstream once fixed.
        # yamllint disable-line rule:line-length
        image: ghcr.io/pixie-io/postgres:14-alpine-pl2@sha256:e442f0b696dde800a5347fa54d982c87bc1db3edddc64bdb18731e3ed6e84bad
        command: ['sh', '-c',
                  'until pg_isready -h ${PL_POSTGRES_HOSTNAME} -p ${PL_POSTGRES_PORT}; do
                  echo "waiting for postgres";
                  sleep 2;
                  done;']
        envFrom:
        - configMapRef:
            name: pl-db-config
      containers:
      - name: updater
        image: cloud-plugin-load_db:latest
        envFrom:
        - configMapRef:
            name: pl-db-config
        - configMapRef:
            name: pl-domain-config
        - configMapRef:
            name: pl-tls-config
        volumeMounts:
        - name: certs
          mountPath: /certs
        env:
        - name: PL_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_USERNAME
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pl-db-secrets
              key: PL_POSTGRES_PASSWORD
        - name: PL_JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: cloud-auth-secrets
              key: jwt-signing-key
        - name: PL_PLUGIN_SERVICE
          valueFrom:
            configMapKeyRef:
              name: pl-service-config
              key: PL_PLUGIN_SERVICE
        - name: PL_PLUGIN_REPO
          value: "pixie-io/pixie-plugin"
        - name: PL_GH_API_KEY
          valueFrom:
            secretKeyRef:
              name: pl-github-secrets
              key: PL_GH_API_KEY
              optional: true
      restartPolicy: Never
      volumes:
      - name: pl-db-secrets
        secret:
          secretName: pl-db-secrets
      - name: certs
        secret:
          secretName: service-tls-certs
  backoffLimit: 1
  parallelism: 1
  completions: 1
