apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: pl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        plane: control
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.4
        command:
        - etcd-operator
        # Uncomment to act for resources in all namespaces. More information in doc/user/clusterwide.md
        #- -cluster-wide
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PL_ETCD_TLS_CERTS
          valueFrom:
            secretKeyRef:
              key: peer.key
              name: etcd-peer-tls-certs
