---
name: mirror-releases
on:
  release:
    types: [released]
permissions:
  contents: read
jobs:
  sync_image:
    permissions:
      contents: read
      packages: write
    runs-on: oracle-16cpu-64gb-x86-64
    steps:
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772  # v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772  # v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772  # v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USER }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b  # v5.4.0
      with:
        go-version-file: 'go.mod'
    - name: install regbot
      shell: bash
      run: go install github.com/regclient/regclient/cmd/regbot@v0.4.8
    - name: sync images
      shell: bash
      run: |
        cd scripts/regclient
        regbot once --config regbot_releases.yaml
