apiVersion: v1
kind: Service
metadata:
  name: pl-etcd-client
  labels:
    app: etcd
    etcd_cluster: pl-etcd
spec:
  ports:
  - name: etcd-client
    port: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: pl-etcd
  labels:
    app: etcd
    etcd_cluster: pl-etcd
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pl-etcd
  labels:
    app: etcd
    etcd_cluster: pl-etcd
spec:
  serviceName: pl-etcd
  selector:
    matchLabels:
      app: etcd
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      name: pl-etcd
      labels:
        app: etcd
        etcd_cluster: pl-etcd
        plane: control
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.4.3
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: server
        command:
        - /bin/sh
        - -c
        - |
          PEERS="pl-etcd-0=https://pl-etcd-0.pl-etcd.${POD_NAMESPACE}.svc:2380,pl-etcd-1=https://pl-etcd-1.pl-etcd.${POD_NAMESPACE}.svc:2380,pl-etcd-2=https://pl-etcd-2.pl-etcd.${POD_NAMESPACE}.svc:2380"
          exec etcd --name ${HOSTNAME} \
            --data-dir /var/etcd/data \
            --initial-advertise-peer-urls https://${HOSTNAME}.pl-etcd.${POD_NAMESPACE}.svc:2380 \
            --listen-peer-urls https://0.0.0.0:2380 \
            --listen-client-urls https://0.0.0.0:2379 \
            --advertise-client-urls https://${HOSTNAME}.pl-etcd.${POD_NAMESPACE}.svc:2379 \
            --initial-cluster-token pl-etcd-cluster-1 \
            --initial-cluster ${PEERS} \
            --initial-cluster-state new \
            --peer-client-cert-auth=true \
            --peer-trusted-ca-file=/etc/etcdtls/member/peer-tls/peer-ca.crt \
            --peer-cert-file=/etc/etcdtls/member/peer-tls/peer.crt \
            --peer-key-file=/etc/etcdtls/member/peer-tls/peer.key \
            --client-cert-auth=true \
            --trusted-ca-file=/etc/etcdtls/member/server-tls/server-ca.crt \
            --cert-file=/etc/etcdtls/member/server-tls/server.crt \
            --key-file=/etc/etcdtls/member/server-tls/server.key
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "10"
        - name: ETCD_AUTO_COMPACTION_MODE
          value: revision
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl --endpoints=https://localhost:2379 --cert=/etc/etcdtls/client/etcd-tls/etcd-client.crt
              --key=/etc/etcdtls/client/etcd-tls/etcd-client.key --cacert=/etc/etcdtls/client/etcd-tls/etcd-client-ca.crt
              endpoint status
          failureThreshold: 3
          initialDelaySeconds: 1
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/etcd
          name: etcd-data
        - mountPath: /etc/etcdtls/member/peer-tls
          name: member-peer-tls
        - mountPath: /etc/etcdtls/member/server-tls
          name: member-server-tls
        - mountPath: /etc/etcdtls/client/etcd-tls
          name: etcd-client-tls
      volumes:
      - name: member-peer-tls
        secret:
          secretName: etcd-peer-tls-certs
      - name: member-server-tls
        secret:
          secretName: etcd-server-tls-certs
      - name: etcd-client-tls
        secret:
          secretName: etcd-client-tls-certs
      - emptyDir: {}
        name: etcd-data
